spring:
    #application:
       # name: Config-Default
    boot:
        admin:
            client:
                url: http://localhost:1111

#Telling where to look for eureka
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true

#exposing all the endpoints for admin server
management:
    endpoints:
        web:
            exposure:
                include: '*'
