#If we are using yml then the format for the cipher text must enclosed within single quotes, for .properties files no need
spring:
    main:
        banner-mode: true
  # application:
  #   name: EMPLOYEE-QA-SERVICE
    boot:
        admin:
            client:
              url: http://localhost:1111/

#Telling where to look for eureka
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true

#exposing all the endpoints for admin server
management:
    endpoints:
        web:
            exposure:
                include: '*'
    info:
        java:
            enabled: false
            
logging:
    level:
        root: INFO

server:
#8081
    port: '{cipher}2331a6feb24876312b27c642e9264eb8a07e4a4b76192e687802ad043b3ed7e9'
